spelling/grammar update along with some other misc updates
raspdevpy/ccdoc pull request #90
Opened 2024-07-19 19:24 UTC by naem-less

i did update some function descriptions, explanations etc. as well to either be stated more clear or to remove some redundant stuff

i tried to fix everything i came across. i didnt update the entire docs to fix grammar though, just the most prevalent ones (im looking at you `$let`)

i don't think i broke any explanations or examples since i didn't touch things i don't know as well

2024-07-19 19:59 UTC, NervN commented on guide/Variables/let.md
> +The first value will only exist umtil cc ends its execution,the second will still be accessable until next bot restart (every 5d)
until*

2024-07-19 20:00 UTC, NervN commented on guide/Text/Object/ObjectIncrease.md
> +To increase a key value, if they key doesn't exist, it will create one and set to that value
"the key" not "they key"

2024-07-19 20:12 UTC, NervN commented on guide/Guide/5.comment.md
> +In some cases you may want to comment out more than one line.
"specific part of it" meaning got removed. can you add it back in your own way.
by specific part, it means commenting a section of code that exists in one line and not commenting the whole line, like:
"Hello $username?/*, How*/ are you?"

to comment out `, How`

2024-07-19 20:14 UTC, NervN commented on guide/Guide/6.variables.md
> +### How to define a permanent variable.
no dot at the end

2024-07-19 20:15 UTC, NervN commented on guide/Guide/6.variables.md
> +Another type of permanent variable are the **user** variables.
```
Another type of permanent variable is the **user** variable
```

2024-07-19 20:17 UTC, NervN commented on guide/Guide/7.array.md
> +As you may know, array functions mostly work based on element indices.
in this context, use indexes. to be related to the name index in function description
(they both correct)

2024-07-19 20:18 UTC, NervN commented on guide/Guide/7.array.md
> +However, you may want to use arrays to store some data accros executions/commands, that has to keep track of all changes among the executions.
across

2024-07-19 20:20 UTC, NervN commented on guide/Text/textSplit/textSplit.md
> +Splits the provided text with `seperator` and returns an array. To access them use: [$arrayGet](./../Array/arrayGet.md) or other array functions
it does not "return" anything

2024-07-19 20:24 UTC, NervN commented on guide/Text/Components/awaitButton.md
> +The maximum time the bot waits for a user to click a button.
this part was updated in the main branch, the calculation was fixed there

2024-07-19 20:44 UTC, NervN commented on guide/Text/only/onlyIf.md
> +Continue the execution only if certain [expression](../../CodeReferences/ref.expression.md) is satisfied, otherwise top the execution and send the error message.
top > stop

2024-07-19 20:48 UTC, NervN commented on guide/Random/randomTextBiased.md
> +The more weight a text has, the more likely it it to be selected
it is to be selected

2024-07-21 21:04 UTC, thatkev requested changes

2024-07-21 21:04 UTC, thatkev commented on guide/Bot/ping.md
`$ping` needs to be separated from `ms`, `$pingms` is not a function.

Try to do this instead:
```
`$ping`ms » `50`ms
```

2024-07-22 07:39 UTC, thatkev commented on guide/Bot/ping.md
Feel free to do this.

2024-07-26 00:41 UTC, NervN commented on guide/Other/syntax.md
> +As the [`$username`](../Member/username.md) documentation will tell you, that by default it will return the exrcutor's name, but if you want to return someone else username you will need to do an inp
exrcutor > executor

2024-07-26 00:46 UTC, NervN commented on guide/Timeout/userSetTimeout.md
> +Sets a user timeout, so the user cannot talk/interact with the server.
in the server

2024-07-26 00:55 UTC, NervN commented on guide/Tutorials/5.confession.md
> +    * To respond tothe user, you can do so with `$interactionReply[message]` where message is the text you would like to display:
tothe > to the

2024-08-02 21:22 UTC, merged